version: "3.8"

services:
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/dev"
    volumes:
      - ./conf/:/conf/
      - ./instance/data:/data
      - ./instance/import:/var/lib/neo4j/import
      - ./instance/logs:/var/lib/neo4j/logs
      - ./instance/plugins:/plugins
    # Simple check testing whether the port 7474 is opened.
    # If so, the instance running inside the container is considered as "healthy".
    # This status can be checked using the "docker ps" command.
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
